In [2]:
#openCV for finding the average hue of bananas for master's thesis


#imports
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from os import listdir

#This was used for batch processing, disregard
files = os.listdir('.')
for i in range(len(files)):
    pass


#Using off the shelf classifier by mrnugget
banana_cascade = cv2.CascadeClassifier('banana_classifier.xml')

#read in image
old_img = cv2.imread('7-3.jpg', cv2.IMREAD_COLOR)
img = cv2.resize(old_img, (0,0), fx=0.2, fy=0.2)

#convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#start cascade
bans = banana_cascade.detectMultiScale(img, minSize = (3,3))
#find and draw boundaries of found banana
for (x, y, w, h) in bans:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,0), 2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]

#convert image to hsv
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

#define roi based on classified banana
roi = hsv[x:x+w, y:y+h]

print(roi[0][0:5])

[[104 200  97]
 [105 197  96]
 [104 199  96]
 [106 191  95]
 [105 191  96]]


In [ ]:
#We can see the HSV values for the first five pixels

In [3]:
#We have all that we want, lets find the average hue for these pixels

temp = []
for list in roi:
    for number in list:
        for x in number:
            temp.append(x)

hues = []
for i in range(0, len(temp),3):
    if temp[i] > 5 and temp[i] < 50:
        hues.append(temp[i])

print(sum(hues) / len(hues))

16.8041178153


In [ ]:
#We have an avg hueof 16.8, which is what we would expect.  A less ripe banana will 
#have a higher hue